name = "rm-boot-backend"
main = "src/server.ts"
compatibility_date = "2026-03-28"
compatibility_flags = [ "nodejs_compat" ]

[build]
command = "npm install && npm run build"

[vars]
NODE_VERSION = "20"

[build.upload]
format = "modules"

[alias]
"sharp" = "node_modules/pino/browser.js"
"puppeteer" = "node_modules/pino/browser.js"
"fluent-ffmpeg" = "node_modules/pino/browser.js"
"@ffmpeg-installer/ffmpeg" = "node_modules/pino/browser.js"